# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            Storyteller
tagline:          'Beautiful storytelling experience.'
description:      'Because everyone has a story to tell.'
url:              http://techapj.com
logo:			  '/images/profile.jpg'
paginate:         20

# Custom vars
author:
  name:         'Storyteller'
  twitter:      https://twitter.com/
  github:       https://github.com/
  google_plus:	https://plus.google.com/

version:          1.0.0
